export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_MINIMAL_AMOUNT = 'FETCH_MINIMAL_AMOUNT';
export const FETCH_ESTIMATED_AMOUNT = 'FETCH_ESTIMATED_AMOUNT';
export const SET_EXCHANGE_FROM = 'SET_EXCHANGE_FROM';
export const SET_EXCHANGE_TO = 'SET_EXCHANGE_TO';
